### ISSUE TITLE
Warning in Log : min and max in common parameter for settings and status are null

### ISSUE THREAD

**Issue by SurfGargano** [iobroker-community-adapters/ioBroker.homeconnect#17]
Version 0.0.32
State value to set for "homeconnect.0.SIEMENS-HS858GXB6-68A40E05FFA6.status.Cooking_Oven_Status_CurrentCavityTemperature" has value "23" greater than max "null" homeconnect.0	2021-05-19 15:33:42.61

This results from settings the min and max parameter in common as null 
example :

{
  "type": "state",
  "common": {
    "name": "Alarm",
    "type": "number",
    "role": "indicator",
    "write": true,
    "read": true,
    "unit": "seconds",
    "min": null,
    "max": null
  },
  "native": {},
  "from": "system.adapter.homeconnect.0",
  "user": "system.user.admin",
  "ts": 1621431255833,
  "_id": "homeconnect.0.SIEMENS-HS858GXB6-68A40E05FFA6.settings.BSH_Common_Setting_AlarmClock",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by gitknd** [comment]
same here (maybe since admin 5.x)

**Comment by n3ucr0n** [comment]
Same here since Admin 5




homeconnect.0 | 2021-05-27 11:39:36.745 | warn | Selected program is empty: {"val":null,"ack":true,"ts":1622108376740,"q":0,"from":"system.adapter.homeconnect.0","user":"system.user.admin","lc":1622108376740}
-- | -- | -- | --
homeconnect.0 | 2021-05-27 11:39:25.194 | warn | State "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.programs.selected.options.BSH_Common_Option_ProgramProgress" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2021-05-27 11:39:25.188 | warn | State "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.programs.selected.options.ConsumerProducts_CoffeeMaker_Option_FlowRate" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2021-05-27 11:39:25.187 | warn | State "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.programs.selected.options.ConsumerProducts_CoffeeMaker_Option_FillQuantity" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2021-05-27 11:39:25.187 | warn | State "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.programs.selected.options.ConsumerProducts_CoffeeMaker_Option_BeanAmount" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2021-05-27 11:39:25.186 | warn | State "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.programs.selected.options.ConsumerProducts_CoffeeMaker_Option_CoffeeTemperature" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2021-05-27 11:39:24.695 | warn | Selected program is empty: {"val":null,"ack":true,"ts":1622108364692,"q":0,"from":"system.adapter.homeconnect.0","user":"system.user.admin","lc":1622108364692}
homeconnect.0 | 2021-05-27 11:38:59.721 | warn | State value to set for "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.status.ConsumerProducts_CoffeeMaker_Status_BeverageCounterHotWater" has value "26993" greater than max "null"
homeconnect.0 | 2021-05-27 11:38:59.720 | warn | State value to set for "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.status.ConsumerProducts_CoffeeMaker_Status_BeverageCounterHotMilk" has value "11" greater than max "null"
homeconnect.0 | 2021-05-27 11:38:59.719 | warn | State value to set for "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.status.ConsumerProducts_CoffeeMaker_Status_BeverageCounterFrothyMilk" has value "12" greater than max "null"
homeconnect.0 | 2021-05-27 11:38:59.719 | warn | State value to set for "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.status.ConsumerProducts_CoffeeMaker_Status_BeverageCounterCoffeeAndMilk" has value "800" greater than max "null"
homeconnect.0 | 2021-05-27 11:38:59.718 | warn | State value to set for "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.status.ConsumerProducts_CoffeeMaker_Status_BeverageCounterCoffee" has value "531" greater than max "null"
homeconnect.0 | 2021-05-27 11:38:59.715 | warn | State value to set for "homeconnect.0.SIEMENS-TI9558X1DE-68A40E3F653E.status.ConsumerProducts_CoffeeMaker_Status_BeverageCounterRistrettoEspresso" has value "63" greater than max "null"

**Comment by o0shojo0o** [comment]
The problem is still present with version 0.0.33 .
![image](https://user-images.githubusercontent.com/19333515/120533989-a0eee200-c3e1-11eb-8875-400f4bf11ced.png)

**Comment by TA2k** [comment]
Please delete all device in the object tree manually.

**Comment by o0shojo0o** [comment]
Yes on the idea am also just come ;) 
Problem is solved!
